config/routes.rb
Rails.application.routes.draw do
  resources :customers
  resources :addresses
  resources :providers
  resources :products
  resources :sales
  resources :products

  get '/upload/index', to: 'upload#index'
  post '/upload/upload_file', to: 'upload#upload_file'
  root 'upload#index'

end

app/models/provider.rb
class Provider < ActiveRecord::Base
  belongs_to :address
  has_many :products
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  before_action :set_provider, only: [:show, :edit, :update, :destroy]

  # GET /providers
  # GET /providers.json
  def index
    @providers = Provider.all
  end

  # GET /providers/1
  # GET /providers/1.json
  def show
  end

  # GET /providers/new
  def new
    @provider = Provider.new
  end

  # GET /providers/1/edit
  def edit
  end

  # POST /providers
  # POST /providers.json
  def create
    @provider = Provider.new(provider_params)

    respond_to do |format|
      if @provider.save
        format.html { redirect_to @provider, notice: 'Provider was successfully created.' }
        format.json { render :show, status: :created, location: @provider }
      else
        format.html { render :new }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providers/1
  # PATCH/PUT /providers/1.json
  def update
    respond_to do |format|
      if @provider.update(provider_params)
        format.html { redirect_to @provider, notice: 'Provider was successfully updated.' }
        format.json { render :show, status: :ok, location: @provider }
      else
        format.html { render :edit }
        format.json { render json: @provider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providers/1
  # DELETE /providers/1.json
  def destroy
    @provider.destroy
    respond_to do |format|
      format.html { redirect_to providers_url, notice: 'Provider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_provider
      @provider = Provider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def provider_params
      params.require(:provider).permit(:name, :address_id)
    end
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/providers/_form.html.erb
<%= form_for(@provider) do |f| %>
  <% if @provider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@provider.errors.count, "error") %> prohibited this provider from being saved:</h2>

      <ul>
      <% @provider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address_id %><br>
    <%= f.text_field :address_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providers/edit.html.erb
<h1>Editing Provider</h1>

<%= render 'form' %>

<%= link_to 'Show', @provider %> |
<%= link_to 'Back', providers_path %>

app/views/providers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Providers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providers.each do |provider| %>
      <tr>
        <td><%= provider.name %></td>
        <td><%= provider.address %></td>
        <td><%= link_to 'Show', provider %></td>
        <td><%= link_to 'Edit', edit_provider_path(provider) %></td>
        <td><%= link_to 'Destroy', provider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Provider', new_provider_path %>

app/views/providers/new.html.erb
<h1>New Provider</h1>

<%= render 'form' %>

<%= link_to 'Back', providers_path %>

app/views/providers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @provider.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @provider.address %>
</p>

<%= link_to 'Edit', edit_provider_path(@provider) %> |
<%= link_to 'Back', providers_path %>